### ISSUE TITLE
Can't disassemble methods mentioning a type parameter

### ISSUE THREAD

**Issue by benjamin-hodgson** [kevin-montrose/Sigil#63]
Repro:

```csharp
class C<T>
{
    public T M() => default;
}

class Program
{
    static void Main(string[] args)
    {
        var x = new C<string>();

        Disassembler<Func<string>>.Disassemble(x.M);
    }
}
```

Error:

```
Unhandled Exception: System.ArgumentException: A BadImageFormatException has been thrown while parsing the signature. This is likely due to lack of a generic context. Ensure genericTypeArguments and genericMethodArguments are provided and contain enough context. ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format.
 (Exception from HRESULT: 0x8007000B)
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.RuntimeModule.ResolveMember(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at Sigil.Disassembler`1.ReadOperands(Module mod, OpCode op, Byte[] cil, Int32 instrStart, Int32 operandStart, IDictionary`2 pLookup, IDictionary`2 lLookup, Int32& advance)
   at Sigil.Disassembler`1.ReadOp(Module mod, Byte[] cil, Int32 ix, IDictionary`2 pLookup, IDictionary`2 lLookup, PrefixTracker prefixes, LabelTracker labels, List`1 labelAccumulator, Operation`1& op)
   at Sigil.Disassembler`1.GetOperations(Module mod, Byte[] cil, IEnumerable`1 ps, IEnumerable`1 ls, LabelTracker labels, IList`1 exceptions, List`1 labelAccumulator, List`1 needsInference)
   at Sigil.Disassembler`1.Disassemble(DelegateType del)
   at test.Program.Main(String[] args) in /Users/Benjamin/Desktop/test/Program.cs:line 17
```

**Comment by benjamin-hodgson** [comment]
Seems like it's not specifically about the return type. It happens whenever the method body mentions a type param directly. All of these reproduce the bug:

* `default(T)`
* `new T` (with an appropriate `where`)
* `AGenericClass<T>.Foo()`
* `AGenericMethod<T>()`
